### ISSUE TITLE
Move API throttling to a leaky bucket algorithm

### ISSUE THREAD

**Issue by achadee** [vend/developer-wiki#3]
A lot of modern APIs are moving away from timed interval throttling to leaky bucket which allows for a more consistent distributed load.

Check it out here!
https://en.wikipedia.org/wiki/Leaky_bucket

You can still achieve the same API limitations without freezing your API for 5 minutes!

**Comment by pzurek** [comment]
Thank for the suggestion. It is something we have considered in the past, just not very high on the priority list. However, the first step we're taking to speed things up is increasing the page sizes and making the API faster. Most endpoints of the API 2.0 deliver 10000 objects in a single request, which means that most resources can be obtained in just a few requests.

**Comment by achadee** [comment]
A lot of our throttling issues are obtained through post requests (creating 1000's of products). Are you guys addressing this? I read over the docs and I didn't see anything for creating products so I'm not sure 😄

**Comment by pzurek** [comment]
Bulk write operations are also something we are considering. Feel free to create a separate issue for that too. If a lot of people end up 👍 -ing it, we may look at it with a bit more priority.

**Comment by pzurek** [comment]
I think we can close this one for now in favour of #5
